[tool.poetry]
name = "tp"
version = "0.1.0"
description = ""
authors = ["Raphael Nepomuceno <58113327+rphln@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
zstandard = "^0.15.2"
ujson = "^4.0.2"
scikit-learn = "^0.24.1"
pandas = "^1.2.3"
nltk = "^3.6.1"
Flask = "^1.1.2"

[tool.poetry.dev-dependencies]
ipykernel = "^5.5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
